### ISSUE TITLE
Message should be in quotations

### ISSUE THREAD

**Issue by DefaultDaddy** [ITU-BDSA2024-GROUP9/Chirp#4]
In order to live up to the requirements as a student, the message should be wrapped in quotations in the csv file.

PS I have already looked into what might be causing it, and it is definitely the CSVWriter that is configured incorrectly for what we need. If you try to escape the quotes like you normally would, then the message will have three quotes on each side.

Acceptance criteria:
- There should be one quote on the left side and one on the right

**Comment by JKlarlund** [comment]
Is fixed with https://github.com/ITU-BDSA2024-GROUP9/Chirp/commit/6adb29c4d580589614f7e6a47677e338838feb8a
